name: remote ssh command
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "ftp.cartaosaudeprevencao.com.br"
        username: "cartaosaudeprevencao"
        password: "cap2020"
        port: 21
        script: |
          ls